trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: "20"
  ACR_NAME: "ielsplatformcr.azurecr.io" # example: elsregistry
  IMAGE_NAME: "iels-sso-web-app"
  IMAGE_TAG: "$(Build.BuildId)"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(NODE_VERSION)"
    displayName: "Install Node.js"

  - script: |
      npm ci
    displayName: "Install dependencies"

  - script: |
      npm test
    displayName: "Run tests"

  - script: |
      npm run build
    displayName: "Build React app"

  - task: DockerInstaller@0
    displayName: "Install Docker"

  - script: |
      echo "Building Docker image..."
      docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG) .
    displayName: "Build Docker image"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "Azure-ELS-Connection"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(ACR_NAME)
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)
    displayName: "Push image to ACR"
