trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: "20"
  DOCKERHUB_USERNAME: "$(dockerhubUser)"
  DOCKERHUB_PASSWORD: "$(dockerhubPass)"
  IMAGE_NAME: "iels-sso-web-app"
  IMAGE_TAG: "$(Build.BuildId)"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(NODE_VERSION)"
    displayName: "Install Node.js"

  - script: npm ci
    displayName: "Install dependencies"

  - script: npm test
    displayName: "Run tests"

  - script: npm run build
    displayName: "Build React app"

  - task: DockerInstaller@0
    displayName: "Install Docker"

  - script: |
      echo "Logging into Docker Hub..."
      echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin

      echo "Building Docker image..."
      docker build -t $(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG) .

      echo "Pushing image..."
      docker push $(DOCKERHUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)
    displayName: "Build and push Docker image to Docker Hub"
